# 服务
server:
  port: 8077

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#hibernate:
# 反向数据库配置
#ddl-auto: update
# 控制台显示执行的sql语句
#show-sql: true